### ISSUE TITLE
Wrong url of Duke.tar.gz

### ISSUE THREAD

**Issue by dongb5** [Cysu/open-reid#11]
Hi!
I have successfully downloaded 'Market-1501-v15.09.15.zip' from google drive, but the url of 'Duke.tar.gz' in the code showed 'Error 404'. Any help?

By the way, I have downloaded a file named 'DukeMTMC_reID.zip' before. Is it same to 'Duke.tar.gz'?

Thanks!

**Comment by Cysu** [comment]
@dongb5 Thank you very much for reporting the issue. It seems that the authors have changed the link and name of the dataset a little bit. I have fixed it in the recent [commit](https://github.com/Cysu/open-reid/commit/39f03c475ddecdfb5683479438ea3c4655bb2dc2). You can directly put ``DukeMTMC-reID.zip`` to the directory ``examples/data/dukemtmc/raw/``
