### ISSUE TITLE
**AttributeError: 'torch.cuda.ByteTensor' object has no attribute 'neg'** --- New issues along with the update of pytorch 

### ISSUE THREAD

**Issue by wangxiao5791509** [Cysu/open-reid#19]
Hi, recently, the pytorch has updated and the code does not run smoothly in the new pytorch version. The following error occurs, could you please update a new version of the code ? 

Traceback (most recent call last):
  File "examples/triplet_loss.py", line 217, in <module>
    main(parser.parse_args())
  File "examples/triplet_loss.py", line 145, in main
    trainer.train(epoch, train_loader, optimizer)
  File "build/bdist.linux-x86_64/egg/reid/trainers.py", line 31, in train
  File "build/bdist.linux-x86_64/egg/reid/trainers.py", line 80, in _forward
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py", line 224, in __call__
    result = self.forward(*input, **kwargs)
  File "build/bdist.linux-x86_64/egg/reid/loss/triplet.py", line 26, in forward
  File "/usr/local/lib/python2.7/dist-packages/torch/autograd/variable.py", line 826, in __rsub__
    return SubConstant.apply(other, self)
  File "/usr/local/lib/python2.7/dist-packages/torch/autograd/_functions/basic_ops.py", line 130, in forward
    return tensor.neg().add_(constant)
**AttributeError: 'torch.cuda.ByteTensor' object has no attribute 'neg'**

**Comment by Cysu** [comment]
@wangxiao5791509 Seems to be a bug in pytorch v0.2. A quick workaround is to change this line to
```python
dist_an.append(dist[i][mask[i] == 0].min())
```
Also refers to #18.

**Comment by wangxiao5791509** [comment]
@Cysu Thanks for your replay. It worked. However, I found one bug of your paper, after that. When testing, it show me the error: 
![screenshot from 2017-08-15 17 09 51](https://user-images.githubusercontent.com/12805786/29321034-bd3846b6-820b-11e7-8b63-bae57e1f7cbd.png)



I solved this issue using unsqueeze provided by pytorch ... 
![screenshot from 2017-08-15 22 39 06](https://user-images.githubusercontent.com/12805786/29321042-c5cfbc1e-820b-11e7-8cd5-2a95da469259.png)


maybe you should check this ...

**Comment by Cysu** [comment]
@wangxiao5791509 Thank you very much for pointing out this issue! PyTorch changes the behavior quite a bit from v0.12 to v0.2. We will adapt our code base to v0.2 soon. Many thanks again.

**Comment by wangxiao5791509** [comment]
@Cysu That's cool. Waiting for your update of this code. Here, I run the code and test it, the results is (triplet loss + resetnet50 + market1501 + batchsize=64): 
![screenshot from 2017-08-15 22 27 50](https://user-images.githubusercontent.com/12805786/29349754-1130498a-828e-11e7-8305-c146da5af4e9.png)

But the benchmark results is : 
![screenshot from 2017-08-13 22 36 47](https://user-images.githubusercontent.com/12805786/29349763-1d1ceab4-828e-11e7-99b4-e5d78df30251.png)

So, I wonder how can I achieve the performance as high as the benmark results ??
Waiting for your replay. Thank you very much .

**Comment by Cysu** [comment]
@wangxiao5791509 There is a command at the end of each row of the benchmark table. If you only have one GPU, may consider reducing the batch size and learning rate accordingly, please refer to [this](https://cysu.github.io/open-reid/examples/training_id.html#multi-gpu-and-batch-size) section.

**Comment by Cysu** [comment]
The original errors have been fixed in #20.
