### ISSUE TITLE
how to  compute CMC and rank?

### ISSUE THREAD

**Issue by Phoebe-star** [Cysu/open-reid#22]
how to  compute CMC and rank?

**Comment by Cysu** [comment]
Suppose you have 3 gallery samples with ID `0,1,1` and 4 query samples with ID `0,0,1,1`, then you need to

Compute 3x4 pairwise distance matrix `D`, where `D[i, j]` = distance between gallery-i and query-j
Create a query ID list `qids = [0,0,1,1]`
Create a gallery ID list `gids = [0,1,1]`
Then you can call `reid.evaluation_metrics.cmc(D, qids, gids)` to get CMC.

**Comment by Phoebe-star** [comment]
1.why is  ID 0,1,1  ?   it mean the second and the third are the same person ?  
2.so   ID 0,1,1   don't have  like  cuhk03    ID  0000  0001  0002   0003 .....(many ID) ?

**Comment by Cysu** [comment]
1. Yeah, it's just an example. The second and the third belong to the same person identity.
2. It's just an example to help you understand.

**Comment by Phoebe-star** [comment]
cuhk03 is use  val  to  compute  CMC    right?

**Comment by Cysu** [comment]
I am not sure what you refer to. All the results here in open reid are reported on the test set.

**Comment by Phoebe-star** [comment]
hi
what  are the   gallery , query  and  prob ?

**Comment by Linranran** [comment]
@Phoebe-star query is the same means as probe,you have a query(probe)image and then you should find the image that have the same id in the gallery. and  we have a rank list  of the gallery images  ,CMC is caculated based on the list

**Comment by Cysu** [comment]
@Linranran Thank you very much for the explanation!

@Phoebe-star Yes, large distance value implies the pair is probably not the same person, and vice versa.

**Comment by Linranran** [comment]
@Cysu its my pleasure，haha

**Comment by Phoebe-star** [comment]
I   got it   , thanks you   ^^

**Comment by Phoebe-star** [comment]
I have another problem 
how to  select  cuhk03   dataset   validation  to  compute  CMC   ??

every  time  , I  got  a  different  cmc   value

**Comment by liangbh6** [comment]
I have another question in computing CMC and mAP of cuhk03. Open reid gived me the result that rank1 was greater than mAP, but When I read some papers such as “SVDNet for Pedestrian Retrieval”， they showed the results that mAP  was greater than rank1. I'm comfused all the time even after I read Evaluation Metrics in docs of open reid. Could anyone help me figure out that or just point me to some helpful website?

**Comment by Phoebe-star** [comment]
what is your cmc code ?

**Comment by mhiyer** [comment]
> Suppose you have 3 gallery samples with ID `0,1,1` and 4 query samples with ID `0,0,1,1`, then you need to
> 
> Compute 3x4 pairwise distance matrix `D`, where `D[i, j]` = distance between gallery-i and query-j
> Create a query ID list `qids = [0,0,1,1]`
> Create a gallery ID list `gids = [0,1,1]`
> Then you can call `reid.evaluation_metrics.cmc(D, qids, gids)` to get CMC.

I believe the distmat should be a 4x3 matrix.
