### ISSUE TITLE
Do you know how to  use the loss that   oim.py and triplet.py

### ISSUE THREAD

**Issue by Phoebe-star** [Cysu/open-reid#27]
Do you know how to  use the loss that   oim.py and triplet.py

thank you

**Comment by zydou** [comment]
You'd better have a look at [Open-reid Documentation](https://cysu.github.io/open-reid/examples/training_id.html)

**Comment by Cysu** [comment]
@zydou Thanks very much for your answer!

@Phoebe-star Please checkout the code for using the [OIMLoss](https://github.com/Cysu/open-reid/blob/master/examples/oim_loss.py#L118) and [TripletLoss](https://github.com/Cysu/open-reid/blob/master/examples/triplet_loss.py#L125).
