### ISSUE TITLE
tensorflow

### ISSUE THREAD

**Issue by voa18105** [Cysu/open-reid#29]
Hello!
First, I would like to thank you, your system works pretty good and its a great job you are doing! 

My main question is... is there a simple way to convert weights to tensorflow (or keras)? I use the resnet50 in your system, and layers that you had added are complicating the convertation - no open-source tools can deal with it (at least I couldnt find the one who does). And I am a bit scared to do that manually, because I am a beginner in deep learning, and have no any experience in torch also...

Also, I cannot improve performance by using deeper resnets. resnet50 show best result, do you think it can be due to insufficiency of training data?

**Comment by Cysu** [comment]
@voa18105 Yes, as far as I know there is no general pytorch-to-tensorflow converter. I am afraid that you have to first scaffold a resnet50 in tensorflow (examples [1](https://github.com/ry/tensorflow-resnet/blob/master/resnet.py), [2](https://github.com/ppwwyyxx/tensorpack/blob/master/examples/ResNet/resnet_model.py), [3](https://github.com/fchollet/deep-learning-models/blob/master/resnet50.py)), and then copy the weights and biases from pytorch layers to tensorflow layers.

I haven't done experiments with deeper nets yet, but I agree that deeper nets might require more data, and also tuning hyperparameters differently.

**Comment by voa18105** [comment]
Thank you for a prompt answer!
Ok... so I will try to do that manually. Thanks for examples also!
