### ISSUE TITLE
evaluation process

### ISSUE THREAD

**Issue by Edelbert** [Cysu/open-reid#34]
Hello.
I find evaluation process a little bit confusing. I used the script author provided for network training:
`python examples/triplet_loss.py -d cuhk03 -b 32 -a resnet50 --logs-dir logs/triplet_loss/cuhk03-resnet50`
I downloaded cuhk03 dataset, so training process went well and produced evaluation results for allshots, cuhk03 and **market1501**, which I didn't download. How come?

**Comment by zydou** [comment]
Please read the document about [Evaluation Metrics](https://cysu.github.io/open-reid/notes/evaluation_metrics.html)

**Comment by Edelbert** [comment]
@zydou I see, thank you.
