### ISSUE TITLE
Market1501 use fixed query images

### ISSUE THREAD

**Issue by luzai** [Cysu/open-reid#35]
Market 1501 evaluation protocol uses fixed 3368 high-quality images as query. It is because we can easily draw high quality bounding box for query pedestrian. 

In this sense, `reis.datasets.market1501` did not follow the official evaluation protocol. 

``` python
def register(subdir, pattern=re.compile(r'([-\d]+)_c(\d)')):
    fpaths = sorted(glob(osp.join(exdir, subdir, '*.jpg')))
    pids = set()
    for fpath in fpaths:
        fname = osp.basename(fpath)
        pid, cam = map(int, pattern.search(fname).groups())
        if pid == -1: continue  # junk images are just ignored
        assert 0 <= pid <= 1501  # pid == 0 means background
        assert 1 <= cam <= 6
        cam -= 1
        pids.add(pid)
        fname = ('{:08d}_{:02d}_{:04d}.jpg'
                 .format(pid, cam, len(identities[pid][cam])))
        identities[pid][cam].append(fname)
        shutil.copy(fpath, osp.join(images_dir, fname))
    return pids

trainval_pids = register('bounding_box_train')
gallery_pids = register('bounding_box_test')
query_pids = register('query')
```

This may explain why the demo code `python examples/triplet_loss.py -d market1501 ` only has  67.9 mAP much lower than soa. For an visual case, 

![image](https://user-images.githubusercontent.com/14788650/33523983-b05999c4-d84e-11e7-9100-abf9898d76b8.png)

**Comment by zydou** [comment]
Please see issue #16. The code in issue #16 follows the offical splitting. And the author has explained the [reason ](https://github.com/Cysu/open-reid/issues/16#issuecomment-319931144).

**Comment by luzai** [comment]
Indeed, there are little difference between splitting by query person IDs and splitting by query images.
Meanwhile, I am sorry for my mistake, the mAP of original [paper](https://arxiv.org/pdf/1703.07737.pdf) is `69.14` using triplet+batch, and `81.07` after *rerank*. Open-reid has reached excellent `67.9`!

**Comment by zydou** [comment]
The paper used ten crops for test-time augmentation while open-reid not. If applied test-time augmentation in open-reid, the results will be higher.

**Comment by Cysu** [comment]
@zydou Thank you very much for the explanation!

@luzai Thank you for pointing out the issue. Will try my best to fix it.
