### ISSUE TITLE
Triplet Mining

### ISSUE THREAD

**Issue by aytackanaci** [Cysu/open-reid#36]
Hi,
I couldn't find in the code where you select PK images for mini-batch.
Which variation of triplet loss is implemented here?

thanks,
Aytac

**Comment by zydou** [comment]
At here:
https://github.com/Cysu/open-reid/blob/5db4f6b4245b8b24073f19c161a3b869121a1d2c/reid/utils/data/sampler.py#L11-L35

**Comment by aytackanaci** [comment]
Great, thanks.

**Comment by Cysu** [comment]
@zydou, thank you very much for the code pointer!

@aytackanaci, we just randomly 1. choose an identity, 2. choose instances for him/her, 3. repeated until fill up the minibatch.
