### ISSUE TITLE
cuhk(01-03) can't be downloaded

### ISSUE THREAD

**Issue by Niculuse** [Cysu/open-reid#38]
I can not find any other accessible website to download cuhk dataset.I wonder if you can offer a baiduyun link.Thanks！

**Comment by zydou** [comment]
Please visit [this page](http://www.ee.cuhk.edu.hk/~xgwang/CUHK_identification.html) to download CUHK01-03 datasets.

**Comment by Niculuse** [comment]
I tried before.However,I have no access to the download lin in that web.Perhapse I'm in China,and you know what it means.

**Comment by zydou** [comment]
You can try to email the authors of these datasets and ask if there is a Baiduyun link for the datasets.
By the way, the best solution is to find a way to across the Wall.
