### ISSUE TITLE
trained weights available?

### ISSUE THREAD

**Issue by Niculuse** [Cysu/open-reid#40]
Hi! 
I want to know if you can provide the trained module or weights. I'm a new beginner here, and it's too hard for me to train these models from the scratch due to personal computer's bad computing performance and small memory. Still, I wanna evaluate these models performance .Thus, I'll appreciate it if you can provide your best trained checkpoint file of that three different loss function.
Thanks, anyway.

**Comment by Cysu** [comment]
Sorry but I don’t have trained models on hand. Will try to retrain some models when available. Nevertheless, this repo aims at reproducible research more than off-the-shelf industry solution to reid.
