### ISSUE TITLE
Can I know about the rank1 precision of the code?(such as on market1501)

### ISSUE THREAD

**Issue by YunpengZhai** [Cysu/open-reid#41]
I have build a similar project for person reid with pytorch? But somehow, my baseline's rank1 precision is not satisfying. So who could tell me the precision of this code, for example, evaluation on market1501 ?

**Comment by zydou** [comment]
https://github.com/Cysu/open-reid/blob/3293ca79a07ebee7f995ce647aafa7df755207b8/reid/evaluators.py#L82-L98

**Comment by YunpengZhai** [comment]
@zydou thanks, but what I want to know is the result of evaluation. what precision can it get? thanks!

**Comment by zydou** [comment]
Calculate mAP:
https://github.com/Cysu/open-reid/blob/3293ca79a07ebee7f995ce647aafa7df755207b8/reid/evaluation_metrics/ranking.py#L82-L83

Calculate CMC:
https://github.com/Cysu/open-reid/blob/3293ca79a07ebee7f995ce647aafa7df755207b8/reid/evaluation_metrics/ranking.py#L18-L22

**Comment by Cysu** [comment]
Thank you @zydou for the answer!

Please feel free to reopen the issue if there are any further problems, @YunpengZhai
