### ISSUE TITLE
where is the metric_learn.base_metric module?

### ISSUE THREAD

**Issue by Wayne-Yuan** [Cysu/open-reid#48]
I've noticed that there're some import statements in `reid.metric_learning.euclidean` as well as in `reid.metric_learning.kissme` and `reid.metric_learning` that imports the module `metric_learn`or `metric_learn.base_metric`.
However, I fail to locate this module in your package. Does this belong to some reference libraries I overlooked?

**Comment by zydou** [comment]
`python setup.py install` will install these modules:
https://github.com/Cysu/open-reid/blob/3293ca79a07ebee7f995ce647aafa7df755207b8/setup.py#L11-L14

See more information about `metric-learn` at [here](https://all-umass.github.io/metric-learn/).

**Comment by Cysu** [comment]
This one: https://github.com/all-umass/metric-learn

**Comment by Cysu** [comment]
@zydou, thanks so much for the answer! We were about the same time :)

**Comment by Wayne-Yuan** [comment]
wow, you guys commented so quickly. Thanks~~
