### ISSUE TITLE
What does “first_match_break” in evaluators.py mean?

### ISSUE THREAD

**Issue by liminxian** [Cysu/open-reid#53]
Hi, Tong Xiao, Thank you for your great work. There is a question about evaluation as in title. What is the difference between first_match_break==True and first_match_break==False?

Thank you very much!

**Comment by zydou** [comment]
On Market-1501:
>the query will always match the “easiest” positive sample in the gallery while does not care other harder positive samples when computing CMC.

You can read the docs: https://cysu.github.io/open-reid/notes/evaluation_metrics.html.

**Comment by liminxian** [comment]
@zydou I see. Thank you for your reply.

**Comment by Cysu** [comment]
@zydou Thanks a lot!
