### ISSUE TITLE
How to fine-tune a model?

### ISSUE THREAD

**Issue by cooliybob** [Cysu/open-reid#56]
Hi, your library is very convenient to use and I have a question,
I use market1501 dataset to train a resnet50. Is it able to fine-tune the same model using cuhk03 ?
Thanks,

**Comment by Cysu** [comment]
Yeah, roughly you may just

1. create the cuhk03 dataset
2. create the model
3. load from market1501 pretrained parameters
4. fine-tune on cuhk03

**Comment by cooliybob** [comment]
Great answer.
Thanks a lot ~!!!
