### ISSUE TITLE
Results on multi-GPUs is better than on one GPU

### ISSUE THREAD

**Issue by wangchust** [Cysu/open-reid#59]
Does anyone encounter this phenomenon,  results on 4 GPUs are better than on 2GPUs. Results on 2GPUs are better than on 1 GPU. The other parameters are all kept same, including learning rate. Does anyone know why?

**Comment by bnu-wangxun** [comment]
Yes, I have the same problem. I think better performance of  4 GPU  comes from that the average  process of derivative on different GPUs .

**Comment by Cysu** [comment]
Please check [this section](https://cysu.github.io/open-reid/examples/training_id.html#multi-gpu-and-batch-size) on our website.

**Comment by wangchust** [comment]
Thank you @bnulihaixia  and @Cysu . This open-reid framework is really an exitcing work!!!
