### ISSUE TITLE
RandomPairSampler is missing

### ISSUE THREAD

**Issue by jaxony** [Cysu/open-reid#6]
Great library!
The implementation for RandomPairSampler is missing from utils/data/sampler.py. Will it be implemented any time soon? It sounds like something useful for loading input data for a verification task.

**Comment by Cysu** [comment]
We implemented a RandomPairSampler in an earlier version of the library. But later it was removed as the API for learning models with siamese structure and joint embedding was not well designed. A temporary (but maybe better) solution is to generate pairs inside a mini-batch, just like what the triplet loss did.
