### ISSUE TITLE
If i don't have a GPU and CUDA

### ISSUE THREAD

**Issue by yzy1996** [Cysu/open-reid#63]
I don' t have a Nvidia GPU and I can not install CUDA,
How can I run the example, it shows me that :
    {raise AssertionError("Torch not compiled with CUDA enabled")
   AssertionError: Torch not compiled with CUDA enabled}

**Comment by cuhk-hbsun** [comment]
I am a user of open-reid library. If you don't have a GPU, who give you the courage to train a deep model like resnet50?

**Comment by yzy1996** [comment]
I have a GPU of AMD
