### ISSUE TITLE
Problem with the file examine.softmax_loss.py

### ISSUE THREAD

**Issue by SWRDFK** [Cysu/open-reid#83]
When I run the file examine.softmax_loss.py, I met the folowing problem:

from sklearn.utils.extmath import pinvh
ImportError: cannot import name 'pinvh'

So how to solve it?
Thanks

**Comment by djidje** [comment]
I got the same problem, I have tried to solve it creating a virtual environment with pythorch 0.4.0 installed but now I've got a : ModuleNotFoundError: No module named 'reid'
If someone have some advices.

Thanks

**Comment by nik1806** [comment]
I am having the same error. This is probably due to new version of scikit-learn. In version 0.21 of scikit-learn pinvh has been removed. I am working of resolving the issue. Hopefully, i will update soon about the results.

**Comment by nik1806** [comment]
Please downgrade scikit-learn to 0.20. It resolves the error.

But now i am getting the problem of 
ImportError: cannot import name 'imsave' from 'scipy.misc'

**Comment by zyccccc** [comment]
pip install scipy==1.2.1

**Comment by zyccccc** [comment]
pip install scipy==1.2.1
